.PHONY: clean All

All:
	@echo "----------Building project:[ Reversi - Debug ]----------"
	@"$(MAKE)" -f  "Reversi.mk"
clean:
	@echo "----------Cleaning project:[ Reversi - Debug ]----------"
	@"$(MAKE)" -f  "Reversi.mk" clean
