.PHONY: clean All

All:
	@echo "----------Building project:[ reversi1 - Debug ]----------"
	@"$(MAKE)" -f  "reversi1.mk"
clean:
	@echo "----------Cleaning project:[ reversi1 - Debug ]----------"
	@"$(MAKE)" -f  "reversi1.mk" clean
